### PR TITLE
Fix #62 - Multi account support

### LINKED ISSUE #62: Multi user support
The Tidal-plugin supports adding multiple Tidal accounts and selecting a Tidal-account per player.
Has this been considered for the Qobuz-plugin? In a house with a lot of SqueezeBoxes and five users it is a valuable advantage.

### PR DESCRIPTION
**Pull request by michaelherger**
- [x] Allow adding more than one account
- [x] Browse mode (async) API
- [x] Let user select account to use per player
- [x] Scanner mode (sync) API
- [x] Double check cache use: make sure we don't conflict with other users
- [x] Double check prefs access for `token` and `userdata`
- [x] Remove some legacy slack while at it
- [x] Bump version number to 3.0
- [x] Require LMS 8.3 in `install.xml`

### CODE REVIEW

**Comment by darrell-k** [comment]
Hi Michael. `canLossless` in `API/Common` is failing to detect a flac-capable account, so  I can only play MP3s. The thing is, all  Qobuz accounts are studio quality (up to 24/192) these days, so we could probably get rid of this check. Assuming  that's the case in all territories, of course.

**Comment by michaelherger** [comment]
Are you saying there's no more lossy subscription for Qobuz available? That would indeed simplify things. Thanks for the feedback!

**Comment by darrell-k** [comment]
That is the case in the UK, at least. You can still chose to stream MP3, but there is no account that is limited to lossy. Also,the subsciption level limited to "CD quality" has gone. Everyone can have 24/192 if they want it!

**Comment by darrell-k** [comment]
I've had a trawl around various country sites (France, Chile, Argentina, US) and it seems the only subscription plan worldwide is hi-res. Seems to have been that way for 4 years!

**Comment by michaelherger** [comment]
> I've had a trawl around various country sites (France, Chile, Argentina, US) and it seems the only subscription plan worldwide is hi-res. Seems to have been that way for 4 years!

Thanks for the investigation!

**Comment by michaelherger** [comment]
@SamInPgh @darrell-k - I think I'd be ready of a .0 release. What do you think?

**Comment by SamInPgh** [comment]
Sounds good to me. Great job on the multiple account support, by the way. I think there will be some happy users out there.

**Comment by darrell-k** [comment]
Have you forgotten about my  booklet link PR?

**Pull request merged**
